config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
    resources :comments
  end
  root  'pages#index', as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about' => 'pages#about', as: 'about'
  get 'services' => 'pages#services', as: 'services'
  get 'contact' => 'pages#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5}
    
    has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: 'Tintswalo', password: '12345', only: [:destroy]
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy 
        redirect_to post_path(@post)
    end

    private
    def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    names = ['Richard', 'Tintswalo','Bongumusa']
    @random = names.sample
    @time = Time.now
    @title = "Welcome"
  end
  
  def contact
 
  end

  def navbar
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: 'Tintswalo', password: '12345', except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Blog comments:</h3>
<% @post.comments.each do |comment| %>
    <div class="p-3 bg-light border border-grey mb-3">
    <p><strong><%= comment.username %>:<br></strong><%= comment.body %><br> <%= link_to 'Delete', [comment.post, comment], class:'text-red creating_blog' ,method: :delete, data: {confirm: 'Are you sure?'} %></p>
    </div>
<% end %>

app/views/comments/_form.html.erb
<section class="mb-5">
<h5>Add comment</h5>
<%= form_for ([@post, @post.comments.build]) do |f| %>

    <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, class:'form-control'%>
    <%= f.label :Comment %>
    <%= f.text_area :body, class:'form-control' %>
    <%= f.submit "Submit", class:'btn btn-primary mt-3' %>
  </div>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />  
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <%= render 'pages/navbar.html.erb' %>
  <%= yield %>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer>
      <div class="my-footer">
        <div class="foot text-center">
            <p class="text-white words_footer"> Proudly Powered by Bongani Phala | Theme by: Bongani Phala 2020</p>
        </div>
      </div>
  </footer>

app/views/pages/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
<%= image_tag 'rocket.jpeg', class:'logo navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <%= link_to 'Home', home_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Blog', posts_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to "Contact Me", "http://www.bonganiphala.com", :target => "_blank", class:'text-white nav-link' %>
      </li>
    </ul>
  </div>
    <ul class="navbar-nav ml-auto creating_blog">
      <li class="nav-item">
        <%= link_to 'Create a Blog', new_post_path, class:'btn btn-primary' %>
      </li>
    </ul>
</nav>
</body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
    <head>
   
    </head>
<body>
<div class="banner">
    <div class="me">
        <div class="them animate__animated animate__backInDown">
        <h1 class="text-white">Share Your thoughts with the world</h1>
        <hr class="line1">
        <h5 class="text-white"> Create and Read a blog post</h5>
        <%= link_to "Contact Me", "http://www.bonganiphala.com", :target => "_blank", class:'btn btn-primary' %>
        </div>
    </div>
</div>
<%= render 'footer' %>
</body>
</html>

app/views/posts/_post_form.html.erb
<section class="container mt-5">
<h3>Create a New Blog</h3>
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
    <%= f.label :body %>
    <%= f.text_area :body, class:'form-control' %>
    <%= f.submit "Save post", class:'btn btn-primary mt-3' %>
<% end %>
</section>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Delete Post</h1>
<%= render 'posts/post_form.html' %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'posts/post_form.html' %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<body>
<section class="blog_banner">
<div class="contact_us">
<div class="them animate__animated animate__backInDown">
<h1 class="text-white">Check out our Blogs</h1>
<h5 class="text-white">Read away!</h5>
</div>
</div>
</section>

<div class="text-center mt-5">
    <h1>Our latest blogs</h1>
    <hr class="line2">
    <p> Welcome to our blogs, stay updated and enjoy a good reading </p>
</div>

<section class= " wraper" id="post">
<div class=" post_container">
<div class= "text-center article">
<div class="new">
<% @posts.each  do |post| %>
    <div class = " border border-secondary ml-3 mt-3">
        <h3 class="post_title mt-5"><%= post.title %></h3>
        <%= link_to "Read more", post_path(post), class:'btn btn-secondary text-white mb-5' %>
    </div>
<% end %>
</div>


</div>
</div>
</section>
<%= render 'pages/footer' %>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<body>
<h1>Create Post</h1>
<%= render 'posts/post_form.html' %>
<div class="postfooter">
<%= render 'pages/footer' %>
</div>

</body>
</html>

app/views/posts/show.html.erb
<section class="reader_banner">
<div class="contact_us">
<div class="them animate__animated animate__backInDown">
<h1 class="text-white">Read with us</h1>
<h5 class="text-white">“You can never get a cup of tea large enough or a book long enough to suit me.”</h5>
</div>
</div>
</section>

<section class="mb-5 container">
<h1 class="text-center mt-5"><%= @post.title %></h1>
<p><%= @post.body %></p>
<%= link_to 'Edit', edit_post_path(@post), class:'btn btn-warning creating_blog' %>
<%= link_to 'Delete', post_path(@post), class:'btn btn-danger creating_blog', method: :delete, data: {confirm: 'Are you sure?'} %>
<%= link_to 'Back', posts_path, class:'btn btn-success creating_blog' %>


<%= render 'comments/comments' %>
<%= render 'comments/form' %>
</section>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>